---
- name: TP7 Read CSV and compare data
  hosts: Node1
  become: true
  become_user: root
  vars:
    latitude: 48.86
    longitude: 2.33

  tasks:
    - name: Read and save temperature.csv
      ansible.builtin.set_fact:
        content_csv: "{{ lookup('file', '../files/temperature.csv') | community.general.from_csv | unique(attribute='time') | sort(attribute='time') }}"
    - name: Call weather API
      ansible.builtin.uri:
        url: "https://api.open-meteo.com/v1/forecast?latitude={{ latitude }}&longitude={{ longitude }}&current=temperature_2m"
        return_content: true
      register: meteo

    - name: Extract current weather
      ansible.builtin.set_fact:
        current_temp: "{{ (meteo.content | from_json).current }}"

    - name: Print CSV
      ansible.builtin.debug:
        msg: "{{ ((content_csv | get_temp(current_temp.time) | float) < current_temp.temperature_2m)
          | ternary('Il fait plus chaud à Paris','Il fait plus froid à Paris')
          | reverse_string }}"
