---
- name: TP7 Read CSV and compare data
  hosts: Node1
  become: true
  become_user: root

  tasks:
    - name: Read and save temperature.csv
      ansible.builtin.set_fact:
        content_csv: "{{ lookup('file', '../files/temperature.csv').splitlines() }}"

    - name: Delete line
      ansible.builtin.set_fact:
        content_unique: "{{ content_csv | unique }}"

    - name: Sort CSV
      ansible.builtin.set_fact:
        content_sorted: "{{ content_unique | sort }}"

    - name: Print CSV
      ansible.builtin.debug:
        msg: "{{ content_sorted | join('\n') }}"
