---
- name: TP7 Read CSV and compare data
  hosts: Node1
  become: true
  become_user: root

  tasks:
    - name: Read and save temperature.csv
      ansible.builtin.set_fact:
        content_csv: "{{ lookup('file', '../files/temperature.csv').splitlines() | unique | sort }}"

    - name: Print CSV
      ansible.builtin.debug:
        msg: "{{ content_csv | join('\n') }}"
