---
- name: TP3 node1 et 2
  hosts: apache
  become: true
  become_user: root
  vars:
    pck1:
      - apache2
      - mysql-server

  tasks:
    - name: Installation des composants Apache et MySQL
      ansible.builtin.apt:
        name: "{{ pck1 }}"
        state: present
        update_cache: true
      register: apt_installed

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Copy index.html if apache2 is installed
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      when: "'apache2' in ansible_facts.packages"

    - name: Demarrage du service apache
      ansible.builtin.service:
        name: apache2
        state: started
      when: "'apache2' in ansible_facts.packages"

- name: TP3 node3
  hosts: gnc
  become: true
  become_user: root
  vars:
    pck2:
      - git
      - nginx
      - cowsay

  tasks:
    - name: Installation des composants git, nginx et cowsay
      ansible.builtin.apt:
        name: "{{ pck2 }}"
        state: present
        update_cache: true
      register: gnc_installed

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Copy index.html if nginx is installed
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.nginx-debian.html
        mode: '0644'
      when: "'nginx' in ansible_facts.packages"

    - name: Demarrage du service nginx
      ansible.builtin.service:
        name: nginx
        state: started
      when: "'nginx' in ansible_facts.packages"

- name: TP3 all
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Installation ufw
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == "Ubuntu"

    - name: Template pour /etc/jour
      ansible.builtin.template:
        src: ../templates/jour.j2
        dest: /etc/jour
        owner: root
        group: root
        mode: '0644'
