---
- name: TP0
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Vim install
      ansible.builtin.apt:
        name: vim
        state: present

    - name: Pwd verif
      ansible.builtin.file:
        path: /etc/passwd
