---
- name: TP0
  hosts: all
  become: yes

  tasks:
    - name: Vim install
      ansible.builtin.apt:
        name: vim
        state: present
    - name: Pwd verif
      command: test -f /etc/passwd
