---
- name: TP6 wordpress deployment on node2
  hosts: web
  become: true
  become_user: root

  tasks:
    - name: Install Apache2 on node2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Install PHP 7.4+ on node2
      ansible.builtin.apt:
        name: php>=7.4
        state: present

    - name: Download WordPress
      ansible.builtin.get_url:
        url: http://fr.wordpress.org/latest-fr_FR.tar.gz
        dest: /var/www/latest-fr_FR.tar.gz
        mode: '0644'
        force_basic_auth: true

    - name: Unzip WordPress
      ansible.builtin.unarchive:
        src: /var/www/latest-fr_FR.tar.gz
        dest: /var/www/
        remote_src: true

    - name: Delete targz
      ansible.builtin.file:
        path: /var/www/latest-fr_FR.tar.gz
        state: absent

    - name: Configure WordPress
      ansible.builtin.template:
        src: templates/wp-config.php.j2
        dest: /var/www/wordpress/wp-config.php
        force: true
        mode: '0644'
      notify: Apache2 restart

  handlers:
    - name: Apache2 restart
      ansible.builtin.service:
        name: apache2
        state: restarted


- name: TP6 wordpress deployment on node3
  hosts: db
  become: true
  become_user: root
  vars_files:
    - vars/db_vars.yml

  tasks:
    - name: Install MySQLServer 8.0+ on node3
      ansible.builtin.apt:
        name: mysql-server>=8.0
        state: present
        update_cache: true

    - name: Install PyMySQL
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Confirm MySQL Started
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: true

    - name: Create TP6 DB
      community.mysql.mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user with DB acess
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
